#!/usr/bin/env python3
"""Rebuild sitemap.xml and llms.txt from the pages themselves.

sitemap.xml lists exactly the indexable pages of tools/check.py with, for each, the date of the last commit that
touched its file (or today, for a file not yet committed) — a real modification date, never the build date.
llms.txt repeats each page's title and description, so it cannot drift from the HTML. Run from the repo root.
"""
import datetime, html, re, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / 'tools'))
from check import PAGES, SITE_URL


def last_change(path):
    out = subprocess.run(['git', 'log', '-1', '--format=%cs', '--', path], cwd=ROOT, capture_output=True, text=True).stdout.strip()
    dirty = subprocess.run(['git', 'status', '--porcelain', '--', path], cwd=ROOT, capture_output=True, text=True).stdout.strip()
    return datetime.date.today().isoformat() if (dirty or not out) else out


def meta(path):
    s = (ROOT / path).read_text(encoding='utf-8')
    title = html.unescape(re.search(r'<title>(.*?)</title>', s, re.S).group(1).strip())
    desc = html.unescape(re.search(r'<meta name="description" content="([^"]*)"', s).group(1))
    return title, desc


urls = []
for route, path in PAGES.items():
    urls.append('  <url>\n    <loc>%s%s</loc>\n    <lastmod>%s</lastmod>\n  </url>' % (SITE_URL, route, last_change(path)))
(ROOT / 'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n'
    '<!-- Exactly the indexable pages, rebuilt by tools/sitemap.py; lastmod is the last commit that touched the page. -->\n'
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n%s\n</urlset>\n' % '\n'.join(urls), encoding='utf-8')

lines = ['# Kleo AI', '',
    '> Kleo makes complete narrated films from a brief, inside the AI assistant you already use: a treatment, a storyboard, every frame drawn by Google Nano Banana Pro, every shot generated as moving footage by ByteDance Seedance 2.5, one narrator, a 4K 60 fps MP4 you download and publish. Two looks, realistic and animation. A remote MCP server with OAuth.',
    '', '## Pages']
for route, path in PAGES.items():
    t, d = meta(path)
    lines.append('- [%s](%s%s): %s' % (t, SITE_URL, route, d))
lines += ['', '## Published product information (checked 26 September 2026)', '',
    'Film: moving footage generated by Seedance 2.5 from Nano Banana Pro frames, 15 seconds to 5 minutes, realistic or animation look, 16:9 or 9:16, English (default) or Italian narration. Output: 4K 60 fps MP4. Optional AI upscale for a film (Real-ESRGAN + RIFE): the film’s credits again, at least 5, refunded automatically if it cannot be applied. Music track (Suno) and burned-in subtitles on request. Animatic: drawn frames with camera movement and narration, up to 60 seconds, 5 credits. The intake asks in one message: look, film or animatic, AI upscale, music, subtitles, narration language. A vision model checks every picture against the request; your own photos can be the character references.',
    'New accounts receive 7 starter credits, enough for one 5-credit animatic. Films require a credit-pack purchase and enough eligible credits: max(10, ceil(duration_seconds / 2)). Packs: €5 = 10 purchased credits, €15 = 35, €40 = 100; one-off purchases. A 20-second film costs 10 credits; 30 seconds costs 15. After one starter animatic then a €5 pack, the total is 12, not enough for a 30-second film. Confirm usable film credits rather than assuming gifted credits are eligible. Treatment and exact cost are reviewed before rendering.',
    'Download and save files within 7 days; publishing is manual. Current Terms specify a small Kleo mark and require permission before reselling output as your own service. Privacy lists prompts, storyboards and account activity as retained until deletion is requested. Read the full Terms and Privacy for conditions. These are summaries of published policies, not independent production tests.',
    'MCP endpoint: https://mcp.kleooai.com/mcp (Streamable HTTP, OAuth). Custom connector access depends on the assistant, account and workspace. Support: kleooai@gmail.com. Sources: https://kleooai.com/pricing/ https://kleooai.com/faq/ https://kleooai.com/terms.html https://kleooai.com/privacy.html https://kleooai.com/connect/',
    '']
(ROOT / 'llms.txt').write_text('\n'.join(lines), encoding='utf-8')
print('sitemap.xml: %d urls; llms.txt: %d pages' % (len(urls), len(PAGES)))
